import type { IconName } from "./ui/Icon";

export type Era = { name: string; columns: number };

/** The tree's eras, left to right, and how many columns each spans. */
export const ERAS: Era[] = [
  { name: "Ancient Era", columns: 3 },
  { name: "Classical Era", columns: 2 },
  { name: "Medieval Era", columns: 2 },
  { name: "Renaissance Era", columns: 2 },
];

export type Tech = {
  id: string;
  name: string;
  col: number;
  row: number;
  cost: number;
  requires: string[];
  icon: IconName;
  /** What it unlocks, as small icons with captions. */
  unlocks: { icon: IconName; name: string }[];
  /** A deed that speeds it up. */
  boost: string;
};

const t = (
  id: string,
  name: string,
  col: number,
  row: number,
  requires: string[],
  icon: IconName,
  unlocks: [IconName, string][],
  boost: string,
): Tech => ({
  id,
  name,
  col,
  row,
  cost: 30 + col * col * 7 + col * 10,
  requires,
  icon,
  unlocks: unlocks.map(([icon, name]) => ({ icon, name })),
  boost,
});

export const TECHS: Tech[] = [
  t(
    "pottery",
    "Pottery",
    0,
    0,
    [],
    "food",
    [["food", "Granary"]],
    "Found a city",
  ),
  t(
    "husbandry",
    "Animal Husbandry",
    0,
    2,
    [],
    "movement",
    [["map", "Pasture"]],
    "Find horses",
  ),
  t(
    "mining",
    "Mining",
    0,
    4,
    [],
    "production",
    [["production", "Mine"]],
    "Settle near hills",
  ),
  t(
    "sailing",
    "Sailing",
    0,
    6,
    [],
    "anchor",
    [["anchor", "Galley"]],
    "Found a city on the coast",
  ),
  t(
    "irrigation",
    "Irrigation",
    1,
    0,
    ["pottery"],
    "food",
    [["food", "Farm on plains"]],
    "Farm a resource",
  ),
  t(
    "writing",
    "Writing",
    1,
    1,
    ["pottery"],
    "book",
    [["science", "Campus"]],
    "Meet another civilization",
  ),
  t(
    "archery",
    "Archery",
    1,
    2,
    ["husbandry"],
    "bow",
    [["bow", "Archer"]],
    "Kill a unit with a slinger",
  ),
  t(
    "masonry",
    "Masonry",
    1,
    4,
    ["mining"],
    "castle",
    [["castle", "Ancient Walls"]],
    "Build a quarry",
  ),
  t(
    "bronze",
    "Bronze Working",
    1,
    5,
    ["mining"],
    "strength",
    [["strength", "Spearman"]],
    "Kill three barbarians",
  ),
  t(
    "astrology",
    "Astrology",
    1,
    6,
    ["sailing"],
    "faith",
    [["faith", "Holy Site"]],
    "Find a natural wonder",
  ),
  t(
    "wheel",
    "The Wheel",
    2,
    3,
    ["mining", "husbandry"],
    "movement",
    [["movement", "Heavy Chariot"]],
    "Mine a resource",
  ),
  t(
    "currency",
    "Currency",
    3,
    1,
    ["writing"],
    "gold",
    [["gold", "Market"]],
    "Make a trade route",
  ),
  t(
    "riding",
    "Horseback Riding",
    3,
    2,
    ["archery"],
    "movement",
    [["movement", "Horseman"]],
    "Build a pasture",
  ),
  t(
    "iron",
    "Iron Working",
    3,
    5,
    ["bronze"],
    "strength",
    [["strength", "Swordsman"]],
    "Build an iron mine",
  ),
  t(
    "navigation",
    "Celestial Navigation",
    3,
    6,
    ["sailing", "astrology"],
    "anchor",
    [["anchor", "Harbor"]],
    "Improve two sea resources",
  ),
  t(
    "mathematics",
    "Mathematics",
    4,
    1,
    ["currency"],
    "science",
    [["science", "+1 movement at sea"]],
    "Build three districts",
  ),
  t(
    "construction",
    "Construction",
    4,
    3,
    ["masonry", "wheel"],
    "castle",
    [["culture", "Amphitheater"]],
    "Build a water mill",
  ),
  t(
    "shipbuilding",
    "Shipbuilding",
    4,
    6,
    ["navigation"],
    "anchor",
    [["anchor", "Quadrireme"]],
    "Own two galleys",
  ),
  t(
    "engineering",
    "Engineering",
    4,
    4,
    ["wheel"],
    "production",
    [["castle", "Aqueduct"]],
    "Build ancient walls",
  ),
  t(
    "tactics",
    "Military Tactics",
    5,
    2,
    ["mathematics"],
    "strength",
    [["strength", "Pikeman"]],
    "Kill a unit with a spearman",
  ),
  t(
    "apprenticeship",
    "Apprenticeship",
    5,
    4,
    ["currency", "engineering"],
    "production",
    [["production", "Industrial Zone"]],
    "Build three mines",
  ),
  t(
    "machinery",
    "Machinery",
    6,
    3,
    ["iron", "engineering"],
    "production",
    [["bow", "Crossbowman"]],
    "Own three archers",
  ),
  t(
    "education",
    "Education",
    6,
    1,
    ["mathematics", "apprenticeship"],
    "book",
    [["book", "University"]],
    "Earn a Great Scientist",
  ),
  t(
    "stirrups",
    "Stirrups",
    6,
    2,
    ["riding"],
    "movement",
    [["movement", "Knight"]],
    "Have the Feudalism civic",
  ),
  t(
    "engineers",
    "Military Engineering",
    5,
    5,
    ["construction"],
    "castle",
    [["castle", "Medieval Walls"]],
    "Build an aqueduct",
  ),
  t(
    "castles",
    "Castles",
    6,
    5,
    ["engineers"],
    "castle",
    [["castle", "Fortress"]],
    "Have a government with six slots",
  ),
  t(
    "cartography",
    "Cartography",
    7,
    6,
    ["shipbuilding"],
    "map",
    [["anchor", "Caravel"]],
    "Build two harbors",
  ),
  t(
    "production",
    "Mass Production",
    7,
    4,
    ["education", "shipbuilding"],
    "production",
    [["production", "Lumber mill"]],
    "Build a water mill",
  ),
  t(
    "banking",
    "Banking",
    7,
    1,
    ["education", "apprenticeship"],
    "gold",
    [["gold", "Bank"]],
    "Have the Guilds civic",
  ),
  t(
    "gunpowder",
    "Gunpowder",
    7,
    3,
    ["machinery", "apprenticeship"],
    "strength",
    [["strength", "Musketman"]],
    "Build an armory",
  ),
  t(
    "printing",
    "Printing",
    8,
    2,
    ["machinery"],
    "book",
    [["book", "Printing press"]],
    "Build two universities",
  ),
  t(
    "astronomy",
    "Astronomy",
    8,
    0,
    ["education"],
    "eye",
    [["science", "Observatory"]],
    "Build a university next to a mountain",
  ),
  t(
    "siege",
    "Siege Tactics",
    8,
    5,
    ["castles", "gunpowder"],
    "strength",
    [["strength", "Bombard"]],
    "Own two heavy chariots",
  ),
];

export const tech = (id: string) => TECHS.find((t) => t.id === id)!;

/** What the empire knows at the start: the ancient and classical eras
 *  (bar a straggler) and the first of the medieval. */
export const STARTING_TECHS = TECHS.filter(
  (t) =>
    (t.col <= 4 && t.id !== "shipbuilding") ||
    ["tactics", "apprenticeship", "engineers"].includes(t.id),
).map((t) => t.id);

export const CIVICS = [
  "Political Philosophy",
  "Drama and Poetry",
  "Military Training",
  "Defensive Tactics",
  "Recorded History",
  "Theology",
  "Naval Tradition",
  "Feudalism",
  "Civil Service",
  "Mercenaries",
  "Medieval Faires",
  "Guilds",
];
