// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types and the registered `#[react_filter]`s / `#[react_morph_filter]`s (plus
// built-ins). Regenerate via your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BloomParams = { radius: number | string, threshold: number, intensity: number, };
export type BlurParams = { radius: number | string, };
export type BrightnessParams = { amount: number, };
export type ChromaticAberrationParams = { offset: number | string, angle: number | string, 
/**
 * Tangential swirl: the R image rotates by `+rotation` degrees
 * (clockwise, y-down) around the node's center, B by `-rotation`.
 * Plain number in degrees — a scalar magnitude, so transitions unwind
 * linearly through every turn. 0 = purely directional split.
 */
rotation: number, };
export type ContrastParams = { amount: number, };
export type CrossfadeParams = { 
/**
 * 0..1 stagger amount; 0 is the plain uniform crossfade.
 */
spread: number, 
/**
 * Noise feature size in logical px.
 */
scale: number | string, 
/**
 * 0..1 local fade window (fraction of the progress range).
 */
softness: number, 
/**
 * Re-rolls the noise pattern (domain offset).
 */
seed: number, };
export type GamepadAxisChange = { gamepad: number, axis: GamepadAxisName, value: number, };
export type GamepadAxisName = "leftStickX" | "leftStickY" | "leftZ" | "rightStickX" | "rightStickY" | "rightZ" | { "other": number };
export type GamepadButtonChange = { gamepad: number, button: GamepadButtonName, 
/**
 * Digital state after the change (thresholds from `GamepadSettings`).
 */
pressed: boolean, 
/**
 * Analog value in `0.0..=1.0` (triggers report the full range).
 */
value: number, };
export type GamepadButtonName = "south" | "east" | "north" | "west" | "c" | "z" | "leftTrigger" | "leftTrigger2" | "rightTrigger" | "rightTrigger2" | "select" | "start" | "mode" | "leftThumb" | "rightThumb" | "dPadUp" | "dPadDown" | "dPadLeft" | "dPadRight" | { "other": number };
export type GamepadConnected = GamepadConnectedData;
export type GamepadConnectedData = { 
/**
 * Monotonic wire id — never reused across reconnects.
 */
gamepad: number, 
/**
 * OS-provided device name.
 */
name: string, 
/**
 * USB vendor id, when the backend knows it.
 */
vendorId: number | null, 
/**
 * USB product id, when the backend knows it.
 */
productId: number | null, };
export type GamepadDisconnected = GamepadDisconnectedData;
export type GamepadDisconnectedData = { 
/**
 * The wire id the pad was announced under. Retired for good.
 */
gamepad: number, };
export type GamepadInputData = { buttons: Array<GamepadButtonChange>, axes: Array<GamepadAxisChange>, };
export type GamepadInputEvent = GamepadInputData;
export type GamepadRumble = { 
/**
 * Wire id from [`GamepadConnected`].
 */
gamepad: number, 
/**
 * Milliseconds (web-`playEffect`-like). Negative values clamp to 0.
 */
duration: number, 
/**
 * Low-frequency motor intensity, clamped to `0.0..=1.0`.
 */
strongMotor: number, 
/**
 * High-frequency motor intensity, clamped to `0.0..=1.0`.
 */
weakMotor: number, };
export type GamepadStopRumble = { gamepad: number, };
export type GradientMapParams = { angle: number | string, stops: Array<GradientMapStop>, amount: number, };
export type GradientMapStop = { color: string, position?: number, };
export type GrayscaleParams = { amount: number, };
export type HueRotateParams = { angle: number | string, };
export type InvertParams = { amount: number, };
export type KeyDown = KeyboardEventData;
export type KeyUp = KeyboardEventData;
export type KeyboardEventData = { 
/**
 * Layout-aware logical key: the typed character (`"a"`, `"A"`) or a named
 * key (`"Enter"`, `"ArrowLeft"`, `"Escape"`).
 */
key: string, 
/**
 * Layout-independent physical key, W3C `code` style (`"KeyA"`, `"Enter"`).
 */
code: string, 
/**
 * The text produced by the key, if any (respects modifiers/IME). `null` for
 * keys that don't produce text (e.g. arrows, modifiers).
 */
text: string | null, 
/**
 * Whether this is an OS auto-repeat while the key is held.
 */
repeat: boolean, ctrlKey: boolean, shiftKey: boolean, altKey: boolean, 
/**
 * The "Meta"/"Super" key (Windows/Command).
 */
metaKey: boolean, };
export type LinearWipeParams = { angle: number | string, softness: number | string, };
export type OutlineParams = { width: number | string, color: string, softness: number | string, };
export type PinchParams = { 
/**
 * Pinch center, 0..1 across the node rect (0 = left edge).
 */
x: number, 
/**
 * Pinch center, 0..1 across the node rect (0 = top edge).
 */
y: number, 
/**
 * -1 (full bulge) ..= 1 (full pinch); 0 is identity.
 */
strength: number, 
/**
 * Effect radius as a fraction of the node's larger dimension.
 */
radius: number, 
/**
 * Diffuse shading intensity: 0 (unlit, the default), 1 nominal; larger
 * values overdrive, like `brightness`.
 */
light: number, 
/**
 * Direction the light comes FROM: degrees clockwise from +X in screen
 * space (bare number = degrees, `"0.25turn"` etc. accepted). Default
 * -135 = top-left.
 */
lightAngle: number | string, 
/**
 * Specular (white) highlight intensity: 0 (off, the default), 1
 * nominal; larger values overdrive.
 */
gloss: number, 
/**
 * Size of the specular highlight, 0 (a pinpoint) ..= 1 (a broad sheen);
 * default 0.3. Mapped log-wise onto a Blinn-Phong exponent in the shader
 * (128 at 0, ~32 at 0.3, 1 at 1).
 */
glossSize: number, 
/**
 * How the effect meets its rim, 0..=1: 0 is a linear onset (a visible
 * crease, like a pressed coin edge), 0.5 (the default) the classic `u^2`
 * smoothstep-like fade, 1 an imperceptible `u^4` fade-in.
 */
outerSoftness: number, 
/**
 * How the effect peaks at its center, 0..=1: 0 is a cone tip (a pointed
 * pit/peak the lighting shows as a point), 0.5 (the default) a rounded
 * bowl, 1 a broad flat floor. Independent of `outerSoftness`: the
 * profile is `1 - (1 - u^a)^b` with `a`/`b` from the two knobs.
 */
innerSoftness: number, };
export type PixelizeParams = { 
/**
 * Cells across x/y at the mosaic's coarsest (upstream `squaresMin`).
 */
squaresMin: [number, number], 
/**
 * Discrete cell-size levels; `<= 0` for a continuous ramp.
 */
steps: number, };
export type Resize = WindowSize;
export type SaturateParams = { amount: number, };
export type SepiaParams = { amount: number, };
export type ShadowParams = { color: string, offsetX: number | string, offsetY: number | string, spread: number | string, };
export type WindowSize = { width: number, height: number, };

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "gamepad.rumble": GamepadRumble;
  "gamepad.stopRumble": GamepadStopRumble;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
  "gamepad.getAll": { request: null; response: Array<GamepadConnectedData> };
  "window.size": { request: null; response: WindowSize };
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  gamepadConnected: GamepadConnected;
  gamepadDisconnected: GamepadDisconnected;
  gamepadInput: GamepadInputEvent;
  keyDown: KeyDown;
  keyUp: KeyUp;
  resize: Resize;
}

/** Every registered filter name and its params type, split by family.
 *  Augments the empty `BevyFilters` (regular filters — the `filter` and
 *  `backdropFilter` chains) and `BevyMorphFilters` (two-input morph
 *  filters — the `morphFilter` style) registry interfaces in the
 *  `bevy-react` package, so each style field types its names' params. */
declare module "bevy-react" {
  interface BevyFilters {
    bloom: BloomParams;
    blur: BlurParams;
    brightness: BrightnessParams;
    chromaticAberration: ChromaticAberrationParams;
    contrast: ContrastParams;
    gradientMap: GradientMapParams;
    grayscale: GrayscaleParams;
    hueRotate: HueRotateParams;
    invert: InvertParams;
    outline: OutlineParams;
    pinch: PinchParams;
    saturate: SaturateParams;
    sepia: SepiaParams;
    shadow: ShadowParams;
  }
  interface BevyMorphFilters {
    crossfade: CrossfadeParams;
    linearWipe: LinearWipeParams;
    pixelize: PixelizeParams;
  }
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  gamepad: {
    getAll(): Promise<Array<GamepadConnectedData>> { return request("gamepad.getAll", null); },
    rumble(value: GamepadRumble): void { emit("gamepad.rumble", value); },
    stopRumble(value: GamepadStopRumble): void { emit("gamepad.stopRumble", value); },
  },
  window: {
    size(): Promise<WindowSize> { return request("window.size", null); },
  },
} as const;
