// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types. Regenerate via your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BallBounced = { 
/**
 * Which wall it hit.
 */
wall: Wall, 
/**
 * Impact speed (world units/sec), for flavor in the toast.
 */
speed: number, };
export type BallState = { x: number, y: number, vx: number, vy: number, };
export type CubeInfo = { entity: bigint, label: string, };
export type CubesSpawned = { cubes: Array<CubeInfo>, };
export type FollowRandom = null;
export type KeyDown = KeyboardEventData;
export type KeyUp = KeyboardEventData;
export type KeyboardEventData = { 
/**
 * Layout-aware logical key: the typed character (`"a"`, `"A"`) or a named
 * key (`"Enter"`, `"ArrowLeft"`, `"Escape"`).
 */
key: string, 
/**
 * Layout-independent physical key, W3C `code` style (`"KeyA"`, `"Enter"`).
 */
code: string, 
/**
 * The text produced by the key, if any (respects modifiers/IME). `null` for
 * keys that don't produce text (e.g. arrows, modifiers).
 */
text: string | null, 
/**
 * Whether this is an OS auto-repeat while the key is held.
 */
repeat: boolean, ctrlKey: boolean, shiftKey: boolean, altKey: boolean, 
/**
 * The "Meta"/"Super" key (Windows/Command).
 */
metaKey: boolean, };
export type SceneId = "Cubes" | "BouncingBall" | "CrowdedCubes" | "Surface";
export type SelectDemo = { label: string, };
export type SelectScene = SceneId | null;
export type SetCount = number;
export type SetCrt = boolean;
export type SetFollowMode = boolean;
export type Wall = "Left" | "Right" | "Top" | "Bottom" | "Front" | "Back";

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "basicDemo.setCount": SetCount;
  "crowdedCubes.followRandom": FollowRandom;
  "crowdedCubes.setFollowMode": SetFollowMode;
  selectScene: SelectScene;
  "surfaceDemo.setCrt": SetCrt;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
  "pollingDemo.getBall": { request: null; response: BallState };
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  "bevyEventsDemo.ballBounced": BallBounced;
  "crowdedCubes.spawned": CubesSpawned;
  "debug.selectDemo": SelectDemo;
  keyDown: KeyDown;
  keyUp: KeyUp;
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  basicDemo: {
    setCount(value: SetCount): void { emit("basicDemo.setCount", value); },
  },
  crowdedCubes: {
    followRandom(value: FollowRandom): void { emit("crowdedCubes.followRandom", value); },
    setFollowMode(value: SetFollowMode): void { emit("crowdedCubes.setFollowMode", value); },
  },
  pollingDemo: {
    getBall(): Promise<BallState> { return request("pollingDemo.getBall", null); },
  },
  selectScene(value: SelectScene): void { emit("selectScene", value); },
  surfaceDemo: {
    setCrt(value: SetCrt): void { emit("surfaceDemo.setCrt", value); },
  },
} as const;
