// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types and the registered `#[react_filter]`s (plus built-ins). Regenerate via
// your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BallBounced = { 
/**
 * Which wall it hit.
 */
wall: Wall, 
/**
 * Impact speed (world units/sec), for flavor in the toast.
 */
speed: number, };
export type BallState = { x: number, y: number, vx: number, vy: number, };
export type BloomParams = { radius: number | string, threshold: number, intensity: number, };
export type BlurParams = { radius: number | string, };
export type BrightnessParams = { amount: number, };
export type ChromaticAberrationParams = { offset: number | string, angle: number | string, };
export type ContrastParams = { amount: number, };
export type CubeInfo = { entity: bigint, label: string, };
export type CubesSpawned = { cubes: Array<CubeInfo>, };
export type Dissolve = { 
/**
 * 0 = intact, 1 = fully dissolved.
 */
progress: number, };
export type FollowRandom = null;
export type Glitch = { 
/**
 * Overall strength, 0 (clean) ..= 1 (heavily corrupted).
 */
intensity: number, };
export type GrayscaleParams = { amount: number, };
export type HueRotateParams = { angle: number | string, };
export type InvertParams = { amount: number, };
export type KeyDown = KeyboardEventData;
export type KeyUp = KeyboardEventData;
export type KeyboardEventData = { 
/**
 * Layout-aware logical key: the typed character (`"a"`, `"A"`) or a named
 * key (`"Enter"`, `"ArrowLeft"`, `"Escape"`).
 */
key: string, 
/**
 * Layout-independent physical key, W3C `code` style (`"KeyA"`, `"Enter"`).
 */
code: string, 
/**
 * The text produced by the key, if any (respects modifiers/IME). `null` for
 * keys that don't produce text (e.g. arrows, modifiers).
 */
text: string | null, 
/**
 * Whether this is an OS auto-repeat while the key is held.
 */
repeat: boolean, ctrlKey: boolean, shiftKey: boolean, altKey: boolean, 
/**
 * The "Meta"/"Super" key (Windows/Command).
 */
metaKey: boolean, };
export type Resize = WindowSize;
export type Ripple = { 
/**
 * Peak displacement, in px.
 */
amplitude: number, 
/**
 * Wave phase across the layer's half-diagonal, in radians (~2 rings at 12).
 */
frequency: number, 
/**
 * Wave cycles per second.
 */
speed: number, };
export type SaturateParams = { amount: number, };
export type SceneId = "Cubes" | "BouncingBall" | "CrowdedCubes" | "Surface";
export type SelectDemo = { label: string, };
export type SelectScene = SceneId | null;
export type SepiaParams = { amount: number, };
export type SetCount = number;
export type SetCrt = boolean;
export type SetFollowMode = boolean;
export type Wall = "Left" | "Right" | "Top" | "Bottom" | "Front" | "Back";
export type WindowSize = { width: number, height: number, };

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "basicDemo.setCount": SetCount;
  "crowdedCubes.followRandom": FollowRandom;
  "crowdedCubes.setFollowMode": SetFollowMode;
  selectScene: SelectScene;
  "surfaceDemo.setCrt": SetCrt;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
  "pollingDemo.getBall": { request: null; response: BallState };
  "window.size": { request: null; response: WindowSize };
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  "bevyEventsDemo.ballBounced": BallBounced;
  "crowdedCubes.spawned": CubesSpawned;
  "debug.selectDemo": SelectDemo;
  keyDown: KeyDown;
  keyUp: KeyUp;
  resize: Resize;
}

/** Every registered filter name and its params type. Augments the empty
 *  `BevyFilters` registry interface in the `bevy-react` package, so the
 *  `filter` style field types each name's params. */
declare module "bevy-react" {
  interface BevyFilters {
    bloom: BloomParams;
    blur: BlurParams;
    brightness: BrightnessParams;
    chromaticAberration: ChromaticAberrationParams;
    contrast: ContrastParams;
    dissolve: Dissolve;
    glitch: Glitch;
    grayscale: GrayscaleParams;
    hueRotate: HueRotateParams;
    invert: InvertParams;
    ripple: Ripple;
    saturate: SaturateParams;
    sepia: SepiaParams;
  }
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  basicDemo: {
    setCount(value: SetCount): void { emit("basicDemo.setCount", value); },
  },
  crowdedCubes: {
    followRandom(value: FollowRandom): void { emit("crowdedCubes.followRandom", value); },
    setFollowMode(value: SetFollowMode): void { emit("crowdedCubes.setFollowMode", value); },
  },
  pollingDemo: {
    getBall(): Promise<BallState> { return request("pollingDemo.getBall", null); },
  },
  selectScene(value: SelectScene): void { emit("selectScene", value); },
  surfaceDemo: {
    setCrt(value: SetCrt): void { emit("surfaceDemo.setCrt", value); },
  },
  window: {
    size(): Promise<WindowSize> { return request("window.size", null); },
  },
} as const;
