// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types. Regenerate via your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BallBounced = { 
/**
 * Which wall it hit.
 */
wall: Wall, 
/**
 * Impact speed (world units/sec), for flavor in the toast.
 */
speed: number, };
export type BallState = { x: number, y: number, vx: number, vy: number, };
export type CubeInfo = { entity: bigint, label: string, };
export type CubesSpawned = { cubes: Array<CubeInfo>, };
export type DemoId = "BasicUi" | "BevyEvents" | "Polling" | "Animations" | "WorldAnchors" | "Interactions" | "Canvas" | "Scroll" | "EditableText";
export type SelectDemo = DemoId;
export type SetCount = number;
export type Wall = "Left" | "Right" | "Top" | "Bottom" | "Front" | "Back";

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "basicDemo.setCount": SetCount;
  selectDemo: SelectDemo;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
  "pollingDemo.getBall": { request: null; response: BallState };
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  "anchoredDemo.cubesSpawned": CubesSpawned;
  "bevyEventsDemo.ballBounced": BallBounced;
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  basicDemo: {
    setCount(value: SetCount): void { emit("basicDemo.setCount", value); },
  },
  pollingDemo: {
    getBall(): Promise<BallState> { return request("pollingDemo.getBall", null); },
  },
  selectDemo(value: SelectDemo): void { emit("selectDemo", value); },
} as const;
