/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h05706098439cf7a2: (a: number, b: number, c: any, d: any, e: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h438f37dce69d128a: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h329d00f6bc5af1e3: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h30f53c3256629fcf: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7bbb8e1a1e7ec577: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h08c928d2359d0c00: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd9830cdb0df35191: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0ba6167e1cd737e6_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2dc349ddd4f65d32: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd0cd43bdc11596a9: (a: number, b: number) => any;
export const wasm_bindgen__convert__closures_____invoke__h79bc5c6cf436143b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1f01538afc547f01: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
