// Build the layers-stress UI as vendor.js + app.js (see js/build-lib.mjs for the
// why). Usage: `node build.mjs` (one-shot), `--watch`, or `--prod`.
//
// STRESS_PRESET (optional): a JSON object baked into `src/preset.json` as the
// UI's startup config — the mechanism `--measure` runs use to preset a
// scenario without any Rust-side bindings. Unset, the committed defaults are
// regenerated byte-identical.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { buildVendor, buildApp, watchApp } from "bevy-react/build-lib";

const watch = process.argv.includes("--watch");
const prod = process.argv.includes("--prod");
const cwd = process.cwd();

// ---------------------------------------------------------------------------
// src/preset.json generation (defaults ⊕ STRESS_PRESET overrides).

const DEFAULT_PRESET = {
  n: 20,
  animate: true,
  groupAlpha: true,
  filterMode: "off",
  blur: false,
  animateFilter: false,
  animateSize: false,
};

const FILTER_MODES = ["off", "half", "all"];

function buildPreset() {
  const raw = process.env.STRESS_PRESET;
  let overrides = {};
  if (raw) {
    try {
      overrides = JSON.parse(raw);
    } catch (e) {
      throw new Error(`STRESS_PRESET is not valid JSON: ${e.message}`);
    }
    if (
      typeof overrides !== "object" ||
      overrides === null ||
      Array.isArray(overrides)
    ) {
      throw new Error(`STRESS_PRESET must be a JSON object, got: ${raw}`);
    }
  }
  const unknown = Object.keys(overrides).filter((k) => !(k in DEFAULT_PRESET));
  if (unknown.length > 0) {
    throw new Error(`STRESS_PRESET: unknown key(s) ${unknown.join(", ")}`);
  }
  // Value validation matters here: esbuild strips types without checking and
  // the --measure flow never runs tsc, so a typo'd value would otherwise be
  // baked in silently — and this harness's whole job is measuring the
  // scenario it claims to (a bad filterMode would quietly measure the
  // unfiltered baseline).
  for (const [k, v] of Object.entries(overrides)) {
    if (typeof v !== typeof DEFAULT_PRESET[k]) {
      throw new Error(
        `STRESS_PRESET: ${k} must be a ${typeof DEFAULT_PRESET[k]}, got ${JSON.stringify(v)}`,
      );
    }
  }
  if (
    "filterMode" in overrides &&
    !FILTER_MODES.includes(overrides.filterMode)
  ) {
    throw new Error(
      `STRESS_PRESET: filterMode must be one of ${FILTER_MODES.join("/")}, got ${JSON.stringify(overrides.filterMode)}`,
    );
  }
  return { ...DEFAULT_PRESET, ...overrides };
}

writeFileSync(
  fileURLToPath(new URL("./src/preset.json", import.meta.url)),
  JSON.stringify(buildPreset(), null, 2) + "\n",
);

const vendor = { outfile: "dist/vendor.js", prod, cwd };
const app = { entry: "src/index.tsx", outfile: "dist/app.js", prod, cwd };

await buildVendor(vendor);

if (watch) {
  await watchApp(app);
  console.log("[build] watching app sources (vendor built once)…");
} else {
  await buildApp(app);
  console.log("[build] vendor.js + app.js built");
}
