// Build the layers-stress UI as vendor.js + app.js (see js/build-lib.mjs for the
// why). Usage: `node build.mjs` (one-shot), `--watch`, or `--prod`.
//
// STRESS_PRESET (optional): a JSON object baked into `src/preset.ts` as the
// UI's startup config — the mechanism `--measure` runs use to preset a
// scenario without any Rust-side bindings. Unset, the committed defaults are
// regenerated byte-identical.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { buildVendor, buildApp, watchApp } from "bevy-react/build-lib";

const watch = process.argv.includes("--watch");
const prod = process.argv.includes("--prod");
const cwd = process.cwd();

// ---------------------------------------------------------------------------
// src/preset.ts generation (defaults ⊕ STRESS_PRESET overrides).

const DEFAULT_PRESET = {
  n: 20,
  animate: true,
  groupAlpha: true,
  filterMode: "off",
  blur: false,
  animateFilter: false,
};

const FILTER_MODES = ["off", "half", "all"];

function buildPreset() {
  const raw = process.env.STRESS_PRESET;
  let overrides = {};
  if (raw) {
    try {
      overrides = JSON.parse(raw);
    } catch (e) {
      throw new Error(`STRESS_PRESET is not valid JSON: ${e.message}`);
    }
    if (
      typeof overrides !== "object" ||
      overrides === null ||
      Array.isArray(overrides)
    ) {
      throw new Error(`STRESS_PRESET must be a JSON object, got: ${raw}`);
    }
  }
  const unknown = Object.keys(overrides).filter((k) => !(k in DEFAULT_PRESET));
  if (unknown.length > 0) {
    throw new Error(`STRESS_PRESET: unknown key(s) ${unknown.join(", ")}`);
  }
  // Value validation matters here: esbuild strips types without checking and
  // the --measure flow never runs tsc, so a typo'd value would otherwise be
  // baked in silently — and this harness's whole job is measuring the
  // scenario it claims to (a bad filterMode would quietly measure the
  // unfiltered baseline).
  for (const [k, v] of Object.entries(overrides)) {
    if (typeof v !== typeof DEFAULT_PRESET[k]) {
      throw new Error(
        `STRESS_PRESET: ${k} must be a ${typeof DEFAULT_PRESET[k]}, got ${JSON.stringify(v)}`,
      );
    }
  }
  if (
    "filterMode" in overrides &&
    !FILTER_MODES.includes(overrides.filterMode)
  ) {
    throw new Error(
      `STRESS_PRESET: filterMode must be one of ${FILTER_MODES.join("/")}, got ${JSON.stringify(overrides.filterMode)}`,
    );
  }
  return { ...DEFAULT_PRESET, ...overrides };
}

function writePreset(p) {
  const body = `// GENERATED by build.mjs — do not edit by hand; every build rewrites it.
// Set STRESS_PRESET to a JSON object to bake a startup config into the bundle
// (how \`--measure\` runs preset the UI without touching Rust bindings), e.g.
//   STRESS_PRESET='{"n":500,"filterMode":"all","blur":true}' \\
//     npm run build -w layers-stress-app
// With STRESS_PRESET unset the file regenerates byte-identical to the
// committed defaults below.

/** Which share of items carries a \`filter\` chain (\`half\` = every 2nd item). */
export type FilterMode = "off" | "half" | "all";

export type Preset = {
  n: number;
  animate: boolean;
  groupAlpha: boolean;
  filterMode: FilterMode;
  blur: boolean;
  animateFilter: boolean;
};

export const PRESET: Preset = {
  n: ${JSON.stringify(p.n)},
  animate: ${JSON.stringify(p.animate)},
  groupAlpha: ${JSON.stringify(p.groupAlpha)},
  filterMode: ${JSON.stringify(p.filterMode)},
  blur: ${JSON.stringify(p.blur)},
  animateFilter: ${JSON.stringify(p.animateFilter)},
};
`;
  writeFileSync(
    fileURLToPath(new URL("./src/preset.ts", import.meta.url)),
    body,
  );
}

writePreset(buildPreset());

const vendor = { outfile: "dist/vendor.js", prod, cwd };
const app = { entry: "src/index.tsx", outfile: "dist/app.js", prod, cwd };

await buildVendor(vendor);

if (watch) {
  await watchApp(app);
  console.log("[build] watching app sources (vendor built once)…");
} else {
  await buildApp(app);
  console.log("[build] vendor.js + app.js built");
}
