// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types. Regenerate via your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BenchOp = "Create" | "Append1" | "Append1k" | "Insert1" | "InsertEvery2nd" | "UpdateText1" | "UpdateTextEvery2nd" | "UpdateColor1" | "UpdateColorEvery2nd" | "Swap1" | "SwapEvery2nd" | "Remove1" | "RemoveEvery2nd" | "Clear";
export type BenchStep = { op: BenchOp, n: number, seed: number, };
export type KeyDown = KeyboardEventData;
export type KeyUp = KeyboardEventData;
export type KeyboardEventData = { 
/**
 * Layout-aware logical key: the typed character (`"a"`, `"A"`) or a named
 * key (`"Enter"`, `"ArrowLeft"`, `"Escape"`).
 */
key: string, 
/**
 * Layout-independent physical key, W3C `code` style (`"KeyA"`, `"Enter"`).
 */
code: string, 
/**
 * The text produced by the key, if any (respects modifiers/IME). `null` for
 * keys that don't produce text (e.g. arrows, modifiers).
 */
text: string | null, 
/**
 * Whether this is an OS auto-repeat while the key is held.
 */
repeat: boolean, ctrlKey: boolean, shiftKey: boolean, altKey: boolean, 
/**
 * The "Meta"/"Super" key (Windows/Command).
 */
metaKey: boolean, };
export type StepDone = { js_ms: number, flush_ms: number, };

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "bench.stepDone": StepDone;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  "bench.runStep": BenchStep;
  keyDown: KeyDown;
  keyUp: KeyUp;
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  bench: {
    stepDone(value: StepDone): void { emit("bench.stepDone", value); },
  },
} as const;
