// @generated by bevy-react — do not edit by hand.
// Mirrors the Rust `#[react_message]` / `#[react_request]` / `#[react_event]`
// types. Regenerate via your app's `App::export_react_typescript` exporter.

import {
  emit as rawEmit,
  request as rawRequest,
  addEventListener as rawAddEventListener,
  removeEventListener as rawRemoveEventListener,
} from "bevy-react";

export type BenchOp = "Create1" |"Create1k" | "Create10k" | "Append1k" | "UpdateEvery10th" | "Swap" | "Select" | "Remove" | "Clear";
export type BenchStep = { op: BenchOp, seed: number, };
export type StepDone = { js_ms: number, flush_ms: number, };

/** Every `emit` name and the payload type it carries. */
export interface ReactMessages {
  "bench.stepDone": StepDone;
}

/** Every `request` name and its request/response types. */
export interface ReactRequests {
}

/** Every Bevy → React event name and the payload it carries. */
export interface ReactEvents {
  "bench.runStep": BenchStep;
}

/** Send a typed app message to the Bevy side. */
export function emit<K extends keyof ReactMessages>(name: K, value: ReactMessages[K]): void {
  rawEmit(name, value);
}

/** Send a typed request and await its typed response. */
export function request<K extends keyof ReactRequests>(
  name: K,
  value: ReactRequests[K]["request"],
): Promise<ReactRequests[K]["response"]> {
  return rawRequest(name, value) as Promise<ReactRequests[K]["response"]>;
}

/** Subscribe to a typed Bevy → React event. Returns an unsubscribe fn. */
export function on<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): () => void {
  rawAddEventListener(name, cb as (value: unknown) => void);
  return () => rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Unsubscribe a listener previously passed to `on`/`addEventListener`. */
export function removeEventListener<K extends keyof ReactEvents>(
  name: K,
  cb: (value: ReactEvents[K]) => void,
): void {
  rawRemoveEventListener(name, cb as (value: unknown) => void);
}

/** Structured, fully typed proxy over every message, request, and event. */
export const bevy = {
  emit,
  request,
  on,
  addEventListener: on,
  removeEventListener,
  bench: {
    stepDone(value: StepDone): void { emit("bench.stepDone", value); },
  },
} as const;
