// GENERATED by build.mjs — do not edit by hand; every build rewrites it.
// Set STRESS_PRESET to a JSON object to bake a startup config into the bundle
// (how `--measure` runs preset the UI without touching Rust bindings), e.g.
//   STRESS_PRESET='{"n":500,"filterMode":"all","blur":true}' \
//     npm run build -w layers-stress-app
// With STRESS_PRESET unset the file regenerates byte-identical to the
// committed defaults below.

/** Which share of items carries a `filter` chain (`half` = every 2nd item). */
export type FilterMode = "off" | "half" | "all";

export type Preset = {
  n: number;
  animate: boolean;
  groupAlpha: boolean;
  filterMode: FilterMode;
  blur: boolean;
  animateFilter: boolean;
};

export const PRESET: Preset = {
  n: 20,
  animate: true,
  groupAlpha: true,
  filterMode: "off",
  blur: false,
  animateFilter: false,
};
